/* Generated By:JJTree: Do not edit this line. ASTfrom_clause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTfrom_clause extends SimpleNode {
  public ASTfrom_clause(int id) {
    super(id);
  }

  public ASTfrom_clause(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c8bfe35e9480408c8b81a7b2e562f6a4 (do not edit this line) */
