/* Generated By:JavaCC: Do not edit this line. RookieParserTreeConstants.java Version 7.0.11 */
package edu.berkeley.cs186.database.cli.parser;

public interface RookieParserTreeConstants
{
  public int JJTSQLSTATEMENTLIST = 0;
  public int JJTVOID = 1;
  public int JJTEXECUTABLESTATEMENT = 2;
  public int JJTEXPLAINSTATEMENT = 3;
  public int JJTDROPTABLESTATEMENT = 4;
  public int JJTDROPINDEXSTATEMENT = 5;
  public int JJTRELEASESTATEMENT = 6;
  public int JJTSAVEPOINTSTATEMENT = 7;
  public int JJTROLLBACKSTATEMENT = 8;
  public int JJTBEGINSTATEMENT = 9;
  public int JJTCOMMITSTATEMENT = 10;
  public int JJTINSERTSTATEMENT = 11;
  public int JJTINSERTVALUES = 12;
  public int JJTUPDATESTATEMENT = 13;
  public int JJTSELECTSTATEMENT = 14;
  public int JJTCOMMONTABLEEXPRESSION = 15;
  public int JJTDELETESTATEMENT = 16;
  public int JJTCREATETABLESTATEMENT = 17;
  public int JJTCREATEINDEXSTATEMENT = 18;
  public int JJTCOLUMNDEF = 19;
  public int JJTSELECTCLAUSE = 20;
  public int JJTLIMITCLAUSE = 21;
  public int JJTFROMCLAUSE = 22;
  public int JJTFROM_CLAUSE = 23;
  public int JJTORDERCLAUSE = 24;
  public int JJTJOINEDTABLE = 25;
  public int JJTSELECTCOLUMN = 26;
  public int JJTRESULTCOLUMNNAME = 27;
  public int JJTCOLUMNNAME = 28;
  public int JJTIDENTIFIER = 29;
  public int JJTALIASEDTABLENAME = 30;
  public int JJTCOLUMNVALUECOMPARISON = 31;
  public int JJTNUMERICLITERAL = 32;
  public int JJTINTEGERLITERAL = 33;
  public int JJTLITERAL = 34;
  public int JJTCOMPARISONOPERATOR = 35;
  public int JJTOROPERATOR = 36;
  public int JJTANDOPERATOR = 37;
  public int JJTNOTOPERATOR = 38;
  public int JJTMULTIPLICATIVEOPERATOR = 39;
  public int JJTADDITIVEOPERATOR = 40;
  public int JJTEXPRESSION = 41;
  public int JJTOREXPRESSION = 42;
  public int JJTANDEXPRESSION = 43;
  public int JJTNOTEXPRESSION = 44;
  public int JJTCOMPARISONEXPRESSION = 45;
  public int JJTADDITIVEEXPRESSION = 46;
  public int JJTMULTIPLICATIVEEXPRESSION = 47;
  public int JJTFUNCTIONCALLEXPRESSION = 48;
  public int JJTPRIMARYEXPRESSION = 49;


  public String[] jjtNodeName = {
    "SQLStatementList",
    "void",
    "ExecutableStatement",
    "ExplainStatement",
    "DropTableStatement",
    "DropIndexStatement",
    "ReleaseStatement",
    "SavepointStatement",
    "RollbackStatement",
    "BeginStatement",
    "CommitStatement",
    "InsertStatement",
    "InsertValues",
    "UpdateStatement",
    "SelectStatement",
    "CommonTableExpression",
    "DeleteStatement",
    "CreateTableStatement",
    "CreateIndexStatement",
    "ColumnDef",
    "SelectClause",
    "LimitClause",
    "FromClause",
    "from_clause",
    "OrderClause",
    "JoinedTable",
    "SelectColumn",
    "ResultColumnName",
    "ColumnName",
    "Identifier",
    "AliasedTableName",
    "ColumnValueComparison",
    "NumericLiteral",
    "IntegerLiteral",
    "Literal",
    "ComparisonOperator",
    "OrOperator",
    "AndOperator",
    "NotOperator",
    "MultiplicativeOperator",
    "AdditiveOperator",
    "Expression",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "ComparisonExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "FunctionCallExpression",
    "PrimaryExpression",
  };
}
/* JavaCC - OriginalChecksum=bcdfecdf30be8750fd3d793a159e2343 (do not edit this line) */
